swagger:
  enabled: false
  info:
    title: stratio- Microservice API
    description: stratio- Microservice API Description
    version: v1


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.apache: WARN
    org.eclipse: WARN
    com.netflix: INFO
    com.stratio: INFO


spring:
  datasource:
    url: jdbc:postgresql://poolpostgrestls.anjana.local:10234/postgres?user=motortown_sync&prepareThreshold=0&ssl=true&sslmode=verify-ca&sslcert=/data/stratio/motortown_sync.pem&sslrootcert=/data/stratio/ca-bundle.pem&sslkey=/data/stratio/motortown_sync.key.pk8&loginTimeout=60
    username: motortown_sync
    password:

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        globally_quoted_identifiers: true
        default_schema: motortown
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



  mail:
    host: smtp.gmail.com
    username: tiendaonline@motortown.es
    password: MTAnjana.1234
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

ecommerce: MOTORTOWN
sftphost: 10.20.1.112
sftpuser: motortown_watcher
sftpkey: /data/stratio/motortownwatcher.key
sftpinfolder: /uploads/ingesta_productos_stock/pendiente/
sftpoutfolder: /uploads/ingesta_productos_stock/en_proceso/
schedulerRate: 900000
schedulerCron: 0 15 02,14 * * *
requestauth: https://cc.anjana.local/sso/login?service=https%3A%2F%2Fcc.anjana.local%2Fsso%2Foauth2.0%2FcallbackAuthorize
motortownsync: http://motortownsync.motortown.marathon.mesos:8080/reprocess
sendermail: tiendaonline@motortown.es
receivermail: apaniagua@stratio.com
subjectmail: Validacion de ficheros de producto
