swagger:
  enabled: false
  info:
    title: stratio- Microservice API
    description: stratio- Microservice API Description
    version: v1


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.apache: WARN
    org.eclipse: WARN
    com.netflix: INFO
    com.stratio: INFO


spring:
  datasource:
    url: jdbc:postgresql://poolpostgrestls.anjana.local:10234/postgres?user=motortown_sync&prepareThreshold=0&ssl=true&sslmode=verify-ca&sslcert=/data/stratio/motortown_sync.pem&sslrootcert=/data/stratio/ca-bundle.pem&sslkey=/data/stratio/motortown_sync.key.pk8&loginTimeout=60
    username: motortown_sync
    password:

spring.jpa.properties.hibernate.jdbc.batch_size : 50
spring.jpa.properties.hibernate.order_inserts : true

ecommerce: MOTORTOWN
sftphost: 10.20.1.112
sftpuser: motortown_watcher
sftpkey: /data/stratio/motortownwatcher.key
sftpinfolder: /anjana/motortown_pro/ingesta_productos_stock/pendiente/
sftpoutfolder: /anjana/motortown_pro/ingesta_productos_stock/en_proceso/
schedulerRate: 1800000
spartawfpath: /motortown
spartawfname: motortown-recalculo
spartawfversion: 24
spartaretries: 3
spartahost: sparta.anjana.local/sparta-server
requestauth: https://cc.anjana.local/sso/login?service=https%3A%2F%2Fcc.anjana.local%2Fsso%2Foauth2.0%2FcallbackAuthorize
motortownsync: http://motortownsync.motortown.marathon.mesos:8080/reprocess
