swagger:
  enabled: false
  info:
    title: stratio- Microservice API
    description: stratio- Microservice API Description
    version: v1


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.apache: WARN
    org.eclipse: WARN
    com.netflix: INFO
    jdbc.sqlonly : INFO
    jdbc.resultsettable: INFO
    jdbc.sqltiming: FATAL
    jdbc.audit: FATAL
    jdbc.resultset: FATAL
    jdbc.connection: FATAL


spring:
  datasource:
    url: jdbc:postgresql://poolpostgrestls.anjana.local:10234/postgres?user=fjurado&prepareThreshold=0&reWriteBatchedInserts=true&ssl=true&sslmode=verify-ca&sslcert=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/fjurado.crt&sslrootcert=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/root-ca.crt&sslkey=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/fjurado.pk8&loginTimeout=60
    username: fjurado
    password:

spring.jpa.properties.hibernate.jdbc.batch_size : 50
spring.jpa.properties.hibernate.order_inserts : true

ecommerce: MOTORTOWN
sftphost: 10.20.1.112
sftpuser: motortown_watcher
sftpkey: /home/apaniagua/.ssh/id_rsa
sftpinfolder: /anjana/motortown_pro/ingesta_productos_stock/pendiente/
sftpoutfolder: /anjana/motortown_pro/ingesta_productos_stock/en_proceso/
schedulerRate: 1800000
spartawfpath: /motortown
spartawfname: motortown-recalculo
spartawfversion: 20
spartaretries: 3
spartahost: sparta.anjana.local/sparta-server
requestauth: https://cc.anjana.local/sso/login?service=https%3A%2F%2Fcc.anjana.local%2Fsso%2Foauth2.0%2FcallbackAuthorize
motortownsync: http://10.20.1.65:10078/productscsvfile

server:
  port: 8888