swagger:
  enabled: true
  info:
    title: stratio- Microservice API
    description: stratio- Microservice API Description
    version: v1


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.apache: WARN
    org.eclipse: WARN
    com.netflix: INFO

spring:
  datasource:
    url: jdbc:postgresql://poolpostgrestls.anjana.local:10234/postgres?user=fjurado&prepareThreshold=0&ssl=true&sslmode=verify-ca&sslcert=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/fjurado.crt&sslrootcert=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/root-ca.crt&sslkey=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/fjurado.pk8&loginTimeout=60
    username: fjurado
    password:

sftphost: 10.20.1.112
sftpuser: motortown_watcher
sftpkey: /home/apaniagua/.ssh/id_rsa
sftpinfolder: /anjana/motortown_pro/ingesta_productos_stock/pendiente/
sftpoutfolder: /anjana/motortown_pro/ingesta_productos_stock/en_proceso/
